name = "backend"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmJjYjNiYmQtZmJmZS00OTljLWEyNTctNjg1ZmE3OTliNzhhIiwidGVuYW50X2lkIjoiYTcwMmM1MzY2OGVlMjUwMjIzYjExNDk4YTI0YmQyODc0NmJjMTgzZTM5MTI5MjVjYWJmN2YxNjVmNGIxNGQxMiIsImludGVybmFsX3NlY3JldCI6IjllYTk4MjI2LTMwYzQtNDI5Yi05NWMyLWZiMGRlNDE1YzFhNyJ9.vk6QgJikLDk3AkHLVgbvLwrvh3koF1xWQoIqYVwHDL8"
JWT_SECRET = "mediumissecret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

